package beans;

// Generated 4 juin 2017 11:38:45 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", catalog = "gestion_pv")
public class Etudiant implements java.io.Serializable {

	private int matricule;
	private int code;
	

	private String nom;
	private String prenom;
	private String filieur;
	private Date dateNissance;
	private Set<Pv> pvs = new HashSet<Pv>(0);

	public Etudiant() {
	}

	public Etudiant(int code, String nom, String prenom, String filieur,
			Date dateNissance) {
		this.code = code;
		this.nom = nom;
		this.prenom = prenom;
		this.filieur = filieur;
		this.dateNissance = dateNissance;
	}

	public Etudiant(int  code, String nom, String prenom, String filieur,
			Date dateNissance, Set<Pv> pvs) {
		this.code=code;
		this.nom = nom;
		this.prenom = prenom;
		this.filieur = filieur;
		this.dateNissance = dateNissance;
		this.pvs = pvs;
	}
	
	@Column(name = "code", unique = true, nullable = false)
	public int getCode() {
		return code;
	}

	public void setCode(int code) {
		this.code = code;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "matricule", unique = true, nullable = false)
	public int getMatricule() {
		return this.matricule;
	}

	public void setMatricule(int matricule) {
		this.matricule = matricule;
	}

	@Column(name = "nom", nullable = false, length = 40)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 40)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "filieur", nullable = false, length = 40)
	public String getFilieur() {
		return this.filieur;
	}

	public void setFilieur(String filieur) {
		this.filieur = filieur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateNissance",  length = 0)
	public Date getDateNissance() {
		return this.dateNissance;
	}

	public void setDateNissance(Date dateNissance) {
		this.dateNissance = dateNissance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	public Set<Pv> getPvs() {
		return this.pvs;
	}

	public void setPvs(Set<Pv> pvs) {
		this.pvs = pvs;
	}

}
