package beans;

// Generated 4 juin 2017 11:38:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pv generated by hbm2java
 */
@Entity
@Table(name = "pv", catalog = "gestion_pv")
public class Pv implements java.io.Serializable {

	private Integer idPv;
	private Etudiant etudiant;
	private String description;
	private String type;
	private String path;
	
	private Date date;
	private byte[] image;
	private Set<Senction> senctions = new HashSet<Senction>(0);

	public Pv() {
	}

	public Pv(Etudiant etudiant, String description,String type,String path, Date date, byte[] image,
			Set<Senction> senctions) {
		this.etudiant = etudiant;
		this.description = description;
		this.date = date;
		this.image = image;
		this.senctions = senctions;
		this.type=type;
		this.path=path;
	}
	@Column(name = "type", length = 40)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPV", unique = true, nullable = false)
	public Integer getIdPv() {
		return this.idPv;
	}

	public void setIdPv(Integer idPv) {
		this.idPv = idPv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matricule")
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@Column(name = "description", length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pv")
	public Set<Senction> getSenctions() {
		return this.senctions;
	}

	public void setSenctions(Set<Senction> senctions) {
		this.senctions = senctions;
	}
	@Column(name = "path", length = 3000)
	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
