package beans;

// Generated 4 juin 2017 11:38:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Senction generated by hbm2java
 */
@Entity
@Table(name = "senction", catalog = "gestion_pv")
public class Senction implements java.io.Serializable {

	private Integer idSenction;
	private Pv pv;
	private Examan examan;
	private String type;

	public Senction() {
	}

	public Senction(Pv pv, Examan examan, String type) {
		this.pv = pv;
		this.examan = examan;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSenction", unique = true, nullable = false)
	public Integer getIdSenction() {
		return this.idSenction;
	}

	public void setIdSenction(Integer idSenction) {
		this.idSenction = idSenction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPv")
	public Pv getPv() {
		return this.pv;
	}

	public void setPv(Pv pv) {
		this.pv = pv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idExaman")
	public Examan getExaman() {
		return this.examan;
	}

	public void setExaman(Examan examan) {
		this.examan = examan;
	}

	@Column(name = "type", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
