package beans;

// Generated 31 mai 2017 10:50:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "gestion_pv")
public class User implements java.io.Serializable {

	private Integer idUser;
	private String nom;
	private String login;
	private String mdp;
	private String travaille;
	
	@Column(name = "travaille", nullable = false, length = 40)
	public String getTravaille() {
		return travaille;
	}

	public void setTravaille(String travaille) {
		this.travaille = travaille;
	}

	private int telephone;
	private String type;

	public User() {
	}

	public User(String nom, String login, String mdp, int telephone, String type) {
		this.nom = nom;
		this.login = login;
		this.mdp = mdp;
		this.telephone = telephone;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUser", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "nom", nullable = false, length = 40)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "login", nullable = false, length = 40)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "mdp", nullable = false, length = 40)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@Column(name = "telephone", nullable = false)
	public int getTelephone() {
		return this.telephone;
	}

	public void setTelephone(int telephone) {
		this.telephone = telephone;
	}

	@Column(name = "type", nullable = false, length = 40)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
